# .streamlit/secrets.toml

OPENROUTER_API_KEY = "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" # Sua chave da OpenRouter
DB_CONNECTION_STRING = "postgresql://user:password@host:port/dbname" # Sua string de conexão da Neon (Opcional. Se não fornecida ou inválida, o app usará um banco de dados SQLite local: llm_evaluations.db)
